### ISSUE TITLE
Dashboard not opening

### ISSUE THREAD

**Issue by SiteshSahoo** [cyrus-and/gdb-dashboard#126]
I am seeing no output when I run the command "dashboard -output <some tty>"

But I can see the below errors.. 
```
Cannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 390, in render
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)
```

**Comment by SiteshSahoo** [comment]
Please note that i am using zsh (ohmyzsh) terminal.

**Comment by cyrus-and** [comment]
> Please note that i am using zsh (ohmyzsh) terminal.

I'm sure its not relevant but does the same happen with a regular Bash shell?

Can you show me how did you invoke GDB and what program are you trying to debug?

**Comment by Grazfather** [comment]
Looks like your GDB is using python2

`pi import sys; print(sys.version)`

**Comment by cyrus-and** [comment]
It should work even with Python 2.7+ though.

**Comment by Grazfather** [comment]
Oh, I saw non-ascii characters in the source file, so I assumed it was python3 only.

It could also be that your locale is not set correctly.

```bash
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by SiteshSahoo** [comment]
Hi,

I am invoking gdb in usual way ..  as below 

```
gdb a.out 
GNU gdb (GDB) Fedora 8.1.1-3.fc28
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from a.out...done.
>>> b main
Breakpoint 1 at 0x400f9a: file main.cxx, line 28.
>>> dashboard -output /dev/pts/0
>>> n
The program is not being run.
>>> r
Starting program: /root/fun/cpp/a.out 
Cannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 390, in render
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)

Breakpoint 1, main () at main.cxx:28
28	  std::vector<double> vd{3.14, 8.1, 3.2, 1.0};
>>> 
```
In the output terminal I can see the below 
```
➜  ~ 
--- RELEASED ---

--- EXITED ---

```

Please correct me in case I missed something.
Below is my locale setting 
```
➜  ~ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
➜  ~ 

Even I feel something is wrong about locale settings. Any quick way to fix  these locale errors (in fedora 28) ?

Thanks,
Sitesh
```

**Comment by cyrus-and** [comment]
> ... and what program are you trying to debug?

I was asking because it may be that the source file/name contains non-ASCII characters in places that are not already properly supported by the dashboard. But apparently you are really having problems with your locale settings.

> Any quick way to fix these locale errors (in fedora 28) ?

That's a pretty common issue, I'd google for that.

It could be that the `en_US.UTF-8` is not properly configured. What's the output of `locale -a`? It should contain `en_US.UTF-8`. If that's the case, a quick fix could be to manually `export LC_ALL=en_US.UTF-8`.

**Comment by SiteshSahoo** [comment]
Hi,

I am invoking gdb in usual way ..  as below 

```
gdb a.out 
GNU gdb (GDB) Fedora 8.1.1-3.fc28
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from a.out...done.
>>> b main
Breakpoint 1 at 0x400f9a: file main.cxx, line 28.
>>> dashboard -output /dev/pts/0
>>> n
The program is not being run.
>>> r
Starting program: /root/fun/cpp/a.out 
Cannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 390, in render
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)

Breakpoint 1, main () at main.cxx:28
28	  std::vector<double> vd{3.14, 8.1, 3.2, 1.0};
>>> 
```
In the output terminal I can see the below 
```
➜  ~ 
--- RELEASED ---

--- EXITED ---

```

Please correct me in case I missed something.
Below is my locale setting 
```
➜  ~ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
➜  ~ 

Even I feel something is wrong about locale settings. Any quick way to fix  these locale errors (in fedora 28) ?

Thanks,
Sitesh
```

**Comment by SiteshSahoo** [comment]
Sorry, It got closed by mistake.

I am testing the below c++ program to print any stl container.

```
#include <iostream>
#include <list>
#include <map>
#include <vector>
                                                                                                                                                                                     
using namespace std;

template <template <typename, typename...> class ContainerType,
          typename ValueType, typename... Args>
void print_container(const ContainerType<ValueType, Args...> &c) {
  for (const auto &v : c) {
    std::cout << v << ' ';
  }
  std::cout << '\n';
}

template <typename T, typename U>
std::ostream &operator<<(std::ostream &out, const std::pair<T, U> &p) {
  out << "[" << p.first << ", " << p.second << "]";
  return out;
}

int main() {
  std::vector<double> vd{3.14, 8.1, 3.2, 1.0};
  print_container(vd);

  std::list<int> li{1, 2, 3, 5};
  print_container(li);

  std::map<int, string> map;
  map[1] = "One";
  map[2] = "Two";
  map[3] = "Three";
  print_container(map);
}
```

**Comment by cyrus-and** [comment]
> I am testing the below c++ program to print any stl container.

Yes, there's nothing *fancy* about this file, so it's probably your locale settings.

> It could be that the en_US.UTF-8 is not properly configured. What's the output of locale -a? It should contain en_US.UTF-8. If that's the case, a quick fix could be to manually export LC_ALL=en_US.UTF-8.

Did you try that?

**Comment by SiteshSahoo** [comment]
> Did you try that?

Yes, finally after fixing locale issue, I am able to see the **gdb-dashboard.** 

_What was the problem ?_ 
As mentioned It's a locale issue.
**en_US.UTF-8** was not installed in my system. Hence only 'export' did not work. 

_Solution :_ 
Install **en_US.UTF-8**. 

_Question :_ 
Is it possible to throw a more meaningful error message if required locales are not present/set ?
Next option could be to do it automatically!

Thanks a lot!!

**Comment by Grazfather** [comment]
This is how you fix it on ubuntu:

```bash
  apt update && apt -y install locales
  locale-gen en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US:en
  export LC_ALL=en_US.UTF-8
```
