### ISSUE TITLE
Fails on UTF-8 output.

### ISSUE THREAD

**Issue by hansrodtang** [cyrus-and/gdb-dashboard#17]
I was trying this out on some UTF-8 stuff I made to test things out and it doesn't seem to be able to handle the letter `å`.

```
node_create (line=0x100800600 L"Tre små") at node.c:9
Traceback (most recent call last):
  File "<string>", line 187, in <lambda>
  File "<string>", line 206, in on_stop
  File "<string>", line 243, in build
  File "<string>", line 803, in lines
  File "<string>", line 843, in fetch_frame_info
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 20: ordinal not in range(128)
>>>
```

**Comment by cyrus-and** [comment]
Please give it a try, it should be fixed now. Thanks.

**Comment by hansrodtang** [comment]
Works great! Thanks!
