### ISSUE TITLE
Registers not displaying properly in Multiarch GDB 9.1

### ISSUE THREAD

**Issue by tcwan** [cyrus-and/gdb-dashboard#190]
I'm trying to setup cross-debugging for ARM using gdb-dashboard and QEMU on MacOS Mojave.

I use Macports provided arm-none-eabi-gdb (Ver. 7.9) with Python 2.7.16 integration, and multiarch gdb (Ver. 9.1) with Python 3.7.7 integration.

I've installed the latest version of gdb-dashboard, with layout configured as:
`dashboard -layout registers stack assembly source`

in arm-none-eabi-gdb (Ver. 7.9) the register info is displayed properly.
```
─── Registers ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   r0 0x00000046    r1 0x00000000   r2 0x00000086   r3 0x00000000   r4 0x0000005f     r5 0x00000000   r6 0x00000000   r7 0x00000000   r8 0x00000000   r9 0x00000000  r10 0x00000000
  r11 0x00000000   r12 0x00000000   sp 0x00001087   lr 0x00000028   pc 0x0000006c   cpsr 0x400001d3
─── Stack ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[0] from 0x0000006c in done at min-max.S:61
[1] from 0x00000028 in Reset_Handler at startup.S:15
─── Assembly ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0x0000006c  ? b    0x6c <done>
 0x00000070  ? andeq    r0, r0, r0, lsl #1
 0x00000074  ? andeq    r0, r0, r5, lsl #1
 0x00000078  ? andeq    r0, r0, r0
 0x0000007c  ? andeq    r0, r0, r0
 0x00000080  ? subseq    r0, pc, r6, asr #6
 0x00000084  ? andeq    r0, r0, r7, lsl r0
 0x00000088  ? andeq    r0, r0, r0
 0x0000008c  ? andeq    r0, r0, r0
 0x00000090  ? andeq    r0, r0, r0
─── Source ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 56  exitloop:
 57      LDR  R2, =min
 58      STRB R3, [R2], #1   /* Store min into memory location */
 59      STRB R4, [R2]       /* Store max into memory location */
 60  done:
 61      B    done           /* Done, loop forever */
 62  .end
~
~
~
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

In ggdb (multiarch GDB Ver. 9.1), the register window is giving me the following problem for the registers display:

```
─── Registers ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "<string>", line 532, in render
  File "<string>", line 1907, in lines
ValueError: max() arg is an empty sequence
─── Stack ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[0] from 0x00000000 in _Reset at startup.S:4
─── Assembly ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0x00000000  ? b    0x20 <Reset_Handler>
 0x00000004  ? b    0x4 <_Reset+4>
 0x00000008  ? b    0x8 <_Reset+8>
 0x0000000c  ? b    0xc <_Reset+12>
 0x00000010  ? b    0x10 <_Reset+16>
 0x00000014  ? b    0x14 <_Reset+20>
 0x00000018  ? b    0x18 <_Reset+24>
 0x0000001c  ? b    0x1c <_Reset+28>
 0x00000020  ? ldr    sp, [pc, #4]    ; 0x2c <Reset_Handler+12>
 0x00000024  ? bl    0x30 <START>
─── Source ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
~
~
 1  .section INTERRUPT_VECTOR, "x"
 2  .global _Reset
 3  _Reset:
 4    B Reset_Handler /* Reset */
 5    B . /* Undefined */
 6    B . /* SWI */
 7    B . /* Prefetch Abort */
 8    B . /* Data Abort */
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

is there a fix for this issue?

**Comment by cyrus-and** [comment]
> In ggdb (multiarch GDB Ver. 9.1), the register window is giving me the following problem for the registers display:

What's the output of `info registers` and `maintenance print register-groups` in this case?

You can always customize the list of displayed registers, this is needed for some architectures and it's a GDB limitation AFACT, for example:

    dashboard registers -style list 'r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 sp lr pc cpsr'

**Comment by tcwan** [comment]
Thanks! That worked.

The ARM QEMU instance is configured for `-M virt`.

Output of `info registers`:
```
>>> info registers
r0             0x0                 0
r1             0x0                 0
r2             0x0                 0
r3             0x0                 0
r4             0x0                 0
r5             0x0                 0
r6             0x0                 0
r7             0x0                 0
r8             0x0                 0
r9             0x0                 0
r10            0x0                 0
r11            0x0                 0
r12            0x0                 0
sp             0x0                 0x0 <_Reset>
lr             0x0                 0
pc             0x0                 0x0 <_Reset>
cpsr           0x400001d3          1073742291
fpscr          0x0                 0
fpsid          0x410430f0          1090793712
fpexc          0x0                 0
CLIDR          0xa200023           169869347
AIDR           0x0                 0
CSSELR         0x0                 0
DBGBCR         0x0                 0
ID_PFR0        0x1131              4401
ID_DFR0        0x2010555           33621333
ID_AFR0        0x0                 0
ID_MMFR0       0x10201105          270536965
ID_MMFR1       0x20000000          536870912
ID_MMFR2       0x1240000           19136512
ID_MMFR3       0x2102211           34611729
DBGBCR         0x0                 0
DBGWVR         0x0                 0
MDCCSR_EL0     0x0                 0
DBGBVR         0x0                 0
DBGDIDR        0x3515f021          890630177
DBGBVR         0x0                 0
DBGDRAR        0x0                 0
DBGWCR         0x0                 0
TEECR          0x0                 0
DBGWCR         0x0                 0
DBGWVR         0x0                 0
ID_ISAR0       0x2101110           34607376
ID_ISAR1       0x13112111          319889681
ID_ISAR2       0x21232041          555950145
ID_ISAR3       0x11112131          286335281
ID_ISAR4       0x10011142          268505410
ID_ISAR5       0x0                 0
ID_MMFR4       0x0                 0
ID_ISAR6       0x0                 0
DBGWVR         0x0                 0
MDSCR_EL1      0x0                 0
DBGDSAR        0x0                 0
DBGBCR         0x0                 0
DBGWCR         0x0                 0
DBGBVR         0x0                 0
DBGBCR         0x0                 0
DBGBVR         0x0                 0
DBGWCR         0x0                 0
DBGWVR         0x0                 0
DBGBVR         0x0                 0
DBGBCR         0x0                 0
DBGBVR         0x0                 0
DBGBCR         0x0                 0
CNTP_CVAL      0x0                 0
CNTV_CVAL      0x0                 0
DBGDRAR        0x0                 0
DFSR           0x0                 0
CPACR          0x0                 0
IFSR           0x0                 0
TPIDRURW       0x0                 0
TPIDRURO       0x0                 0
TPIDRPRW       0x0                 0
FCSEIDR        0x0                 0
CONTEXTIDR_EL1 0x0                 0
L2CTLR         0x800000            8388608
L2ECTLR        0x0                 0
TEEHBR         0x0                 0
OSLSR_EL1      0xa                 10
AFSR0_EL1      0x0                 0
AFSR1_EL1      0x0                 0
DUMMY          0x0                 0
ACTLR_EL1      0x0                 0
DUMMY          0x0                 0
TTBR0          0x0                 0
DUMMY          0x0                 0
PAR            0x0                 0
TTBR1          0x0                 0
CTR            0x8444c004          -2075869180
TCMTR          0x0                 0
ACTLR_EL2      0x0                 0
DUMMY          0x0                 0
SCTLR          0xc50078            12910712
MIDR           0x412fc0f1          1093648625
TLBTR          0x0                 0
DUMMY          0x0                 0
VBAR           0x0                 0
PMCR           0x41002000          1090527232
PMCNTENSET     0x0                 0
PMCNTENCLR     0x0                 0
PMOVSR         0x0                 0
PMSELR         0x0                 0
PMCCNTR        0x0                 0
PMUSERENR      0x0                 0
PMINTENSET     0x0                 0
PMINTENCLR     0x0                 0
PMOVSSET       0x0                 0
DBGDSAR        0x0                 0
TTBR1_EL1      0x0                 0
TTBR0_EL1      0x0                 0
DFAR           0x0                 0
WFAR           0x0                 0
IFAR           0x0                 0
MAIR0          0x0                 0
MAIR1          0x0                 0
CNTP_CTL       0x0                 0
CNTKCTL        0x0                 0
TTBCR          0x0                 0
CNTFRQ         0x3b9aca0           62500000
AMAIR0         0x0                 0
CNTV_CTL       0x0                 0
AMAIR1         0x0                 0
PMEVCNTR1      0x0                 0
PMEVCNTR2      0x0                 0
PMEVCNTR3      0x0                 0
PMEVCNTR0      0x0                 0
PMEVTYPER0     0x0                 0
PMEVTYPER1     0x0                 0
PMEVTYPER2     0x0                 0
PMEVTYPER3     0x0                 0
PMCCFILTR      0x0                 0
CBAR           0x8000000           134217728
PAR            0x0                 0
DACR           0x0                 0
```

Output of `maintenance print register-groups`:
```
 Name         Nr  Rel Offset    Size  Type            Groups
 r0            0    0      0       4 long            
 r1            1    1      4       4 long            
 r2            2    2      8       4 long            
 r3            3    3     12       4 long            
 r4            4    4     16       4 long            
 r5            5    5     20       4 long            
 r6            6    6     24       4 long            
 r7            7    7     28       4 long            
 r8            8    8     32       4 long            
 r9            9    9     36       4 long            
 r10          10   10     40       4 long            
 r11          11   11     44       4 long            
 r12          12   12     48       4 long            
 sp           13   13     52       4 *1              
 lr           14   14     56       4 long            
 pc           15   15     60       4 *1              
 ''           16   16     64       0 int0_t          
 ''           17   17     64       0 int0_t          
 ''           18   18     64       0 int0_t          
 ''           19   19     64       0 int0_t          
 ''           20   20     64       0 int0_t          
 ''           21   21     64       0 int0_t          
 ''           22   22     64       0 int0_t          
 ''           23   23     64       0 int0_t          
 ''           24   24     64       0 int0_t          
 cpsr         25   25     64       4 long            
 ''           26   26     68       0 int0_t          
 ''           27   27     68       0 int0_t          
 ''           28   28     68       0 int0_t          
 ''           29   29     68       0 int0_t          
 ''           30   30     68       0 int0_t          
 ''           31   31     68       0 int0_t          
 ''           32   32     68       0 int0_t          
 ''           33   33     68       0 int0_t          
 ''           34   34     68       0 int0_t          
 ''           35   35     68       0 int0_t          
 ''           36   36     68       0 int0_t          
 ''           37   37     68       0 int0_t          
 ''           38   38     68       0 int0_t          
 ''           39   39     68       0 int0_t          
 ''           40   40     68       0 int0_t          
 ''           41   41     68       0 int0_t          
 ''           42   42     68       0 int0_t          
 ''           43   43     68       0 int0_t          
 ''           44   44     68       0 int0_t          
 ''           45   45     68       0 int0_t          
 ''           46   46     68       0 int0_t          
 ''           47   47     68       0 int0_t          
 ''           48   48     68       0 int0_t          
 ''           49   49     68       0 int0_t          
 ''           50   50     68       0 int0_t          
 ''           51   51     68       0 int0_t          
 ''           52   52     68       0 int0_t          
 ''           53   53     68       0 int0_t          
 ''           54   54     68       0 int0_t          
 ''           55   55     68       0 int0_t          
 ''           56   56     68       0 int0_t          
 ''           57   57     68       0 int0_t          
 d0           58   58     68       8 neon_d          
 d1           59   59     76       8 neon_d          
 d2           60   60     84       8 neon_d          
 d3           61   61     92       8 neon_d          
 d4           62   62    100       8 neon_d          
 d5           63   63    108       8 neon_d          
 d6           64   64    116       8 neon_d          
 d7           65   65    124       8 neon_d          
 d8           66   66    132       8 neon_d          
 d9           67   67    140       8 neon_d          
 d10          68   68    148       8 neon_d          
 d11          69   69    156       8 neon_d          
 d12          70   70    164       8 neon_d          
 d13          71   71    172       8 neon_d          
 d14          72   72    180       8 neon_d          
 d15          73   73    188       8 neon_d          
 d16          74   74    196       8 neon_d          
 d17          75   75    204       8 neon_d          
 d18          76   76    212       8 neon_d          
 d19          77   77    220       8 neon_d          
 d20          78   78    228       8 neon_d          
 d21          79   79    236       8 neon_d          
 d22          80   80    244       8 neon_d          
 d23          81   81    252       8 neon_d          
 d24          82   82    260       8 neon_d          
 d25          83   83    268       8 neon_d          
 d26          84   84    276       8 neon_d          
 d27          85   85    284       8 neon_d          
 d28          86   86    292       8 neon_d          
 d29          87   87    300       8 neon_d          
 d30          88   88    308       8 neon_d          
 d31          89   89    316       8 neon_d          
 fpscr        90   90    324       4 long            
 q0           91   91    328      16 neon_q          
 q1           92   92    344      16 neon_q          
 q2           93   93    360      16 neon_q          
 q3           94   94    376      16 neon_q          
 q4           95   95    392      16 neon_q          
 q5           96   96    408      16 neon_q          
 q6           97   97    424      16 neon_q          
 q7           98   98    440      16 neon_q          
 q8           99   99    456      16 neon_q          
 q9          100  100    472      16 neon_q          
 q10         101  101    488      16 neon_q          
 q10         102  102    504      16 neon_q          
 q12         103  103    520      16 neon_q          
 q13         104  104    536      16 neon_q          
 q14         105  105    552      16 neon_q          
 q15         106  106    568      16 neon_q          
 fpsid       107  107    584       4 long            
 fpexc       108  108    588       4 long            
 CLIDR       109  109    592       4 long            cp_regs
 AIDR        110  110    596       4 long            cp_regs
 CSSELR      111  111    600       4 long            cp_regs
 DBGBCR      112  112    604       4 long            cp_regs
 ID_PFR0     113  113    608       4 long            cp_regs
 ID_DFR0     114  114    612       4 long            cp_regs
 ID_AFR0     115  115    616       4 long            cp_regs
 ID_MMFR0    116  116    620       4 long            cp_regs
 ID_MMFR1    117  117    624       4 long            cp_regs
 ID_MMFR2    118  118    628       4 long            cp_regs
 ID_MMFR3    119  119    632       4 long            cp_regs
 DBGBCR      120  120    636       4 long            cp_regs
 DBGWVR      121  121    640       4 long            cp_regs
 MDCCSR_EL0  122  122    644       4 long            cp_regs
 DBGBVR      123  123    648       4 long            cp_regs
 DBGDIDR     124  124    652       4 long            cp_regs
 DBGBVR      125  125    656       4 long            cp_regs
 DBGDRAR     126  126    660       8 long long       cp_regs
 DBGWCR      127  127    668       4 long            cp_regs
 TEECR       128  128    672       4 long            cp_regs
 DBGWCR      129  129    676       4 long            cp_regs
 DBGWVR      130  130    680       4 long            cp_regs
 ID_ISAR0    131  131    684       4 long            cp_regs
 ID_ISAR1    132  132    688       4 long            cp_regs
 ID_ISAR2    133  133    692       4 long            cp_regs
 ID_ISAR3    134  134    696       4 long            cp_regs
 ID_ISAR4    135  135    700       4 long            cp_regs
 ID_ISAR5    136  136    704       4 long            cp_regs
 ID_MMFR4    137  137    708       4 long            cp_regs
 ID_ISAR6    138  138    712       4 long            cp_regs
 DBGWVR      139  139    716       4 long            cp_regs
 MDSCR_EL1   140  140    720       4 long            cp_regs
 DBGDSAR     141  141    724       8 long long       cp_regs
 DBGBCR      142  142    732       4 long            cp_regs
 DBGWCR      143  143    736       4 long            cp_regs
 DBGBVR      144  144    740       4 long            cp_regs
 DBGBCR      145  145    744       4 long            cp_regs
 DBGBVR      146  146    748       4 long            cp_regs
 DBGWCR      147  147    752       4 long            cp_regs
 DBGWVR      148  148    756       4 long            cp_regs
 DBGBVR      149  149    760       4 long            cp_regs
 DBGBCR      150  150    764       4 long            cp_regs
 DBGBVR      151  151    768       4 long            cp_regs
 DBGBCR      152  152    772       4 long            cp_regs
 CNTP_CVAL   153  153    776       8 long long       cp_regs
 CNTV_CVAL   154  154    784       8 long long       cp_regs
 DBGDRAR     155  155    792       4 long            cp_regs
 DFSR        156  156    796       4 long            cp_regs
 CPACR       157  157    800       4 long            cp_regs
 IFSR        158  158    804       4 long            cp_regs
 TPIDRURW    159  159    808       4 long            cp_regs
 TPIDRURO    160  160    812       4 long            cp_regs
 TPIDRPRW    161  161    816       4 long            cp_regs
 FCSEIDR     162  162    820       4 long            cp_regs
 CONTEXTIDR_EL1  163  163    824       4 long            cp_regs
 L2CTLR      164  164    828       4 long            cp_regs
 L2ECTLR     165  165    832       4 long            cp_regs
 TEEHBR      166  166    836       4 long            cp_regs
 OSLSR_EL1   167  167    840       4 long            cp_regs
 AFSR0_EL1   168  168    844       4 long            cp_regs
 AFSR1_EL1   169  169    848       4 long            cp_regs
 DUMMY       170  170    852       4 long            cp_regs
 ACTLR_EL1   171  171    856       4 long            cp_regs
 DUMMY       172  172    860       4 long            cp_regs
 TTBR0       173  173    864       8 long long       cp_regs
 DUMMY       174  174    872       4 long            cp_regs
 PAR         175  175    876       8 long long       cp_regs
 TTBR1       176  176    884       8 long long       cp_regs
 CTR         177  177    892       4 long            cp_regs
 TCMTR       178  178    896       4 long            cp_regs
 ACTLR_EL2   179  179    900       4 long            cp_regs
 DUMMY       180  180    904       4 long            cp_regs
 SCTLR       181  181    908       4 long            cp_regs
 MIDR        182  182    912       4 long            cp_regs
 TLBTR       183  183    916       4 long            cp_regs
 DUMMY       184  184    920       4 long            cp_regs
 VBAR        185  185    924       4 long            cp_regs
 PMCR        186  186    928       4 long            cp_regs
 PMCNTENSET  187  187    932       4 long            cp_regs
 PMCNTENCLR  188  188    936       4 long            cp_regs
 PMOVSR      189  189    940       4 long            cp_regs
 PMSELR      190  190    944       4 long            cp_regs
 PMCCNTR     191  191    948       4 long            cp_regs
 PMUSERENR   192  192    952       4 long            cp_regs
 PMINTENSET  193  193    956       4 long            cp_regs
 PMINTENCLR  194  194    960       4 long            cp_regs
 PMOVSSET    195  195    964       4 long            cp_regs
 DBGDSAR     196  196    968       4 long            cp_regs
 TTBR1_EL1   197  197    972       4 long            cp_regs
 TTBR0_EL1   198  198    976       4 long            cp_regs
 DFAR        199  199    980       4 long            cp_regs
 WFAR        200  200    984       4 long            cp_regs
 IFAR        201  201    988       4 long            cp_regs
 MAIR0       202  202    992       4 long            cp_regs
 MAIR1       203  203    996       4 long            cp_regs
 CNTP_CTL    204  204   1000       4 long            cp_regs
 CNTKCTL     205  205   1004       4 long            cp_regs
 TTBCR       206  206   1008       4 long            cp_regs
 CNTFRQ      207  207   1012       4 long            cp_regs
 AMAIR0      208  208   1016       4 long            cp_regs
 CNTV_CTL    209  209   1020       4 long            cp_regs
 AMAIR1      210  210   1024       4 long            cp_regs
 PMEVCNTR1   211  211   1028       4 long            cp_regs
 PMEVCNTR2   212  212   1032       4 long            cp_regs
 PMEVCNTR3   213  213   1036       4 long            cp_regs
 PMEVCNTR0   214  214   1040       4 long            cp_regs
 PMEVTYPER0  215  215   1044       4 long            cp_regs
 PMEVTYPER1  216  216   1048       4 long            cp_regs
 PMEVTYPER2  217  217   1052       4 long            cp_regs
 PMEVTYPER3  218  218   1056       4 long            cp_regs
 PMCCFILTR   219  219   1060       4 long            cp_regs
 CBAR        220  220   1064       4 long            cp_regs
 PAR         221  221   1068       4 long            cp_regs
 DACR        222  222   1072       4 long            cp_regs
 s0          223    0   1076       4 float           
 s1          224    1   1080       4 float           
 s2          225    2   1084       4 float           
 s3          226    3   1088       4 float           
 s4          227    4   1092       4 float           
 s5          228    5   1096       4 float           
 s6          229    6   1100       4 float           
 s7          230    7   1104       4 float           
 s8          231    8   1108       4 float           
 s9          232    9   1112       4 float           
 s10         233   10   1116       4 float           
 s11         234   11   1120       4 float           
 s12         235   12   1124       4 float           
 s13         236   13   1128       4 float           
 s14         237   14   1132       4 float           
 s15         238   15   1136       4 float           
 s16         239   16   1140       4 float           
 s17         240   17   1144       4 float           
 s18         241   18   1148       4 float           
 s19         242   19   1152       4 float           
 s20         243   20   1156       4 float           
 s21         244   21   1160       4 float           
 s22         245   22   1164       4 float           
 s23         246   23   1168       4 float           
 s24         247   24   1172       4 float           
 s25         248   25   1176       4 float           
 s26         249   26   1180       4 float           
 s27         250   27   1184       4 float           
 s28         251   28   1188       4 float           
 s29         252   29   1192       4 float           
 s30         253   30   1196       4 float           
 s31         254   31   1200       4 float           
*1: Register type's name NULL.
```

**Comment by cyrus-and** [comment]
Thanks!

The problem is that the output of `maintenance print register-groups` is not the one expected, i.e., the `Groups` column is empty for general registers. I wish GDB implemented a stable interface for fetching the list of general register for an architecture...
