### ISSUE TITLE
Error on Debian

### ISSUE THREAD

**Issue by mlncn** [cyrus-and/gdb-dashboard#2]
After obtaining the .gdbinit file and running gdb, Debian (Jessie) Mint has en error.

$ wget -P ~ git.io/.gdbinit
$ gdb

This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 246, in start
  File "<string>", line 199, in load_modules
  File "<string>", line 335, in __init__
  File "<string>", line 362, in add_subcommands
  File "<string>", line 1065, in commands
AttributeError: 'module' object has no attribute 'COMPLETE_EXPRESSION'
/home/mlncn/.gdbinit:1093: Error in sourced command file:
Error while executing Python code.

**Comment by mlncn** [comment]
Sorry, i started this issue when none were reported but took an hour to hit submit!  This is a duplicate and an amplification of #1
