### ISSUE TITLE
gdb.error: Alias already exists: db

### ISSUE THREAD

**Issue by bgirard** [cyrus-and/gdb-dashboard#22]
I get this error from this line:
run('alias -a db = dashboard')

I'm seeing this both in my Ubuntu and Mac machine.

source /home/mozilla/scratch/gdb-dashboard/.gdbinit
>>> 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 289, in start
  File "<string>", line 116, in run
gdb.error: Alias already exists: db
/home/mozilla/scratch/gdb-dashboard/.gdbinit:1198: Error in sourced command file:

**Comment by cyrus-and** [comment]
Do you have another `.gdbinit` file which defines the `db` alias?
I see that you're sourcing GDB dashboard, try to put it in your home directory instead.

**Comment by bgirard** [comment]
I do not:
mozilla@mozgfx-rr-orange-hunter-1:~/scratch/gdb-dashboard$ gdb
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
<...>
(gdb) db
Undefined command: "db".  Try "help".

It appears to only happen if I source it before the program is running:
mozilla@mozgfx-rr-orange-hunter-1:~/scratch/gdb-dashboard$ gdb sleep
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
<...>
(gdb) source /home/mozilla/scratch/gdb-dashboard/.gdbinit
>>> 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 289, in start
  File "<string>", line 116, in run
gdb.error: Alias already exists: db
/home/mozilla/scratch/gdb-dashboard/.gdbinit:1198: Error in sourced command file:

and if I start the program first it's fine:
mozilla@mozgfx-rr-orange-hunter-1:~/scratch/gdb-dashboard$ gdb sleep
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
<...>
(gdb) run 5
Starting program: /bin/sleep 5
^C
Program received signal SIGINT, Interrupt.
0x00007ffff7ad9c30 in __nanosleep_nocancel () at ../sysdeps/unix/syscall-template.S:81
81	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) source /home/mozilla/scratch/gdb-dashboard/.gdbinit
>>>

**Comment by bgirard** [comment]
Ohh it's my fault actually. When I source without the program running I don't into a bad state with no prompt. I was hitting <enter> to get a prompt and was causing GDB to source the script again.

I guess the real issue is that sourcing the dashboard before a program is running give you neither the (gdb) or the >>>> prompt.

**Comment by bgirard** [comment]
I'll refile the issue properly. Sorry for the noise.

**Comment by cyrus-and** [comment]
No problem. Waiting for further details, it seems I cannot reproduce that lack of prompt string you mention.
