### ISSUE TITLE
AttributeError: 'module' object has no attribute 'COMPLETE_EXPRESSION'

### ISSUE THREAD

**Issue by aceamarco** [cyrus-and/gdb-dashboard#227]
I just called wget -P ~ https://git.io/.gdbinit in my home directory and started up gdb and this is the error I'm getting

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 578, in start
  File "<string>", line 465, in load_modules
  File "<string>", line 702, in __init__
  File "<string>", line 728, in add_subcommands
  File "<string>", line 2124, in commands
AttributeError: 'module' object has no attribute 'COMPLETE_EXPRESSION'
(removed for privacy reasons)/.gdbinit:2275: Error in sourced command file:
Error while executing Python code.

I'd really appreciate anyone's help with this — I'm excited to use the dashboard

**Comment by cyrus-and** [comment]
Maybe [this](https://github.com/cyrus-and/gdb-dashboard/wiki/Support-older-GDB-versions) can help.
