### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by lbmeng** [cyrus-and/gdb-dashboard#229]
Using GDB to connect to a QEMU powerpc target, the gdbdashboard reports:

```
─── Registers ───────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "<string>", line 538, in render
  File "<string>", line 1940, in lines
ValueError: max() arg is an empty sequence
```

Is this a known issue?

**Comment by lbmeng** [comment]
"info registers" shows:

```
>>> info registers 
r0             0x0                 0
r1             0xfffff8            16777208
r2             0x0                 0
r3             0x2700000           40894464
r4             0x0                 0
r5             0x0                 0
r6             0x45504150          1162887504
r7             0x4000000           67108864
r8             0x0                 0
r9             0x0                 0
r10            0x0                 0
r11            0x0                 0
r12            0x0                 0
r13            0x0                 0
r14            0x0                 0
r15            0x0                 0
r16            0x0                 0
r17            0x0                 0
r18            0x0                 0
r19            0x0                 0
r20            0x0                 0
r21            0x0                 0
r22            0x0                 0
r23            0x0                 0
r24            0x0                 0
r25            0x0                 0
r26            0x0                 0
r27            0x0                 0
r28            0x0                 0
r29            0x0                 0
r30            0x0                 0
r31            0x0                 0
pc             0xf00000            0xf00000 <_start_e500>
msr            0x0                 0
cr             0x0                 0
lr             0x0                 0x0
ctr            0x0                 0
xer            0x0                 0
acc            0x0                 0
spefscr        0x0                 0
xer            0x0                 0
lr             0x0                 0
ctr            0x0                 0
decr           0x0                 0
srr0           0x0                 0
srr1           0x0                 0
pid            0x0                 0
decar          0x0                 0
csrr0          0x0                 0
csrr1          0x0                 0
dear           0x0                 0
esr            0x0                 0
ivpr           0x0                 0
usprg0         0x0                 0
usprg3         0x0                 0
usprg4         0x0                 0
usprg5         0x0                 0
usprg6         0x0                 0
usprg7         0x0                 0
tbl            0x0                 0
tbu            0x0                 0
sprg0          0x0                 0
sprg1          0x0                 0
sprg2          0x0                 0
sprg3          0x0                 0
sprg4          0x0                 0
sprg5          0x0                 0
sprg6          0x0                 0
sprg7          0x0                 0
tbl            0x0                 0
tbu            0x0                 0
pir            0x0                 0
pvr            0x80210030          -2145320912
dbsr           0x0                 0
dbcr0          0x0                 0
dbcr1          0x0                 0
dbcr2          0x0                 0
iac1           0x0                 0
iac2           0x0                 0
dac1           0x0                 0
dac2           0x0                 0
tsr            0x0                 0
tcr            0x0                 0
ivor0          0x0                 0
ivor1          0x0                 0
ivor2          0x0                 0
ivor3          0x0                 0
ivor4          0x0                 0
ivor5          0x0                 0
ivor6          0x0                 0
ivor7          0x0                 0
ivor8          0x0                 0
ivor9          0x0                 0
ivor10         0x0                 0
ivor11         0x0                 0
ivor12         0x0                 0
ivor13         0x0                 0
ivor14         0x0                 0
ivor15         0x0                 0
spefscr        0x0                 0
bbear          0x0                 0
bbtar          0x0                 0
l1cfg0         0x3820              14368
l1cfg1         0x3820              14368
npidr          0x0                 0
ivor32         0x0                 0
ivor33         0x0                 0
ivor34         0x0                 0
ivor35         0x0                 0
mcsrr0         0x0                 0
mcsrr1         0x0                 0
mcsr           0x0                 0
mcar           0x0                 0
dsrr0          0x0                 0
dsrr1          0x0                 0
sprg8          0x0                 0
sprg9          0x0                 0
mas0           0x0                 0
mas1           0x0                 0
mas2           0x0                 0
mas3           0x0                 0
mas4           0x0                 0
mas6           0x0                 0
pid1           0x0                 0
pid2           0x0                 0
tlb0cfg        0x4110200           68223488
tlb1cfg        0x101cc010          270319632
epr            0x0                 0
mas7           0x0                 0
eplc           0x0                 0
epsc           0x0                 0
hid0           0x0                 0
hid1           0x0                 0
l1csr0         0x0                 0
l1csr1         0x0                 0
mmucsr0        0x0                 0
bucsr          0x0                 0
mmucfg         0x0                 0
svr            0x80e80010          -2132279280
```

**Comment by cyrus-and** [comment]
> Is this a known issue?

Yeah, literally opened by you: #222

**Comment by lbmeng** [comment]
> Yeah, literally opened by you: #222

Oops did not remember this as I had my ARM setup using the trick:

`dashboard registers -style list 'r0 r1 r2 r3 r4 r5 r6 r7 r8 r9 r10 r11 r12 sp lr pc cpsr'`

So this is a powerpc one.

Is there a trick in the initialization script that can dynamically switch the register style based on architecture?

**Comment by cyrus-and** [comment]
There are several possibilities, unfortunately GDB does not make that easy.

You can define utility functions, then call them manually when needed:

```gdb
define setup-arm
dashboard registers -style list '...'
end
```

Or you can place `.gdbinit` files in your projects so that the right `setup-*` function is called every time GDB is started from that project folder. Read more [here](https://github.com/cyrus-and/gdb-dashboard/wiki/Setup-project-configurations).

Or even something more involved that somewhat fetches the architecture from GDB (e.g., `show architecture` or from Python `gdb.selected_frame().architecture().name()`) and acts accordingly.

**Comment by lbmeng** [comment]
Thank you very much. This is very helpful.
