### ISSUE TITLE
Does the script depend on python3?

### ISSUE THREAD

**Issue by Peterchen931** [cyrus-and/gdb-dashboard#271]
My current environment is only python 2.7, and then I use the gdbinit file to output errors.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 586, in start
  File "<string>", line 471, in load_modules
  File "<string>", line 720, in __init__
  File "<string>", line 746, in add_subcommands
  File "<string>", line 2167, in commands
AttributeError: 'module' object has no attribute 'COMPLETE_EXPRESSION'
/root/.gdbinit:2318: Error in sourced command file:

**Comment by cyrus-and** [comment]
Does [this](https://github.com/cyrus-and/gdb-dashboard/wiki/Support-older-GDB-versions) help?

**Comment by Peterchen931** [comment]
Yes, that solves my problem
