### ISSUE TITLE
doesn't work, when source the .gdb-dashboard

### ISSUE THREAD

**Issue by NitroAshi** [cyrus-and/gdb-dashboard#301]
Hi, 
When I source the gdb-dashborad, it says:

`Traceback (most recent call last):`
`  File "<string>", line 1, in <module>`
`  File "<string>", line 593, in start`
`  File "<string>", line 658, in parse_inits`
`gdb.error: /u/myname/.gdbinit.d/init:2375: Error in sourced command file:`
`Error while executing Python code.`
`gdb-dashboard:2375: Error in sourced command file:`
`Error while executing Python code.`

the line 2375 is `python Dashboard.start()`

How can I fix this error. Please help.

the python versiuon is shown under below
` gdb -ex 'python import sys; print(sys.version)' -ex quit`
`GNU gdb (GDB) 13.1`
`For help, type "help".`
`.......`
`Type "apropos word" to search for commands related to "word".`
`3.8.0 (default, Jun 27 2020, 21:48:56)`
`[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]`

**Comment by NitroAshi** [comment]
sorry, I have found that the reason for this is that the file has been sourced twice.
~/gdb-dashboard
~/.gdbinit.d/init
