### ISSUE TITLE
python 2.7.16 failed

### ISSUE THREAD

**Issue by JsBlueCat** [cyrus-and/gdb-dashboard#323]
```
Traceback (most recent call last):
  File "<string>", line 550, in render
  File "<string>", line 2287, in lines
  File "<string>", line 348, in fetch_breakpoints
TypeError: '_sre.SRE_Match' object has no attribute '__getitem__'
```

```
Traceback (most recent call last):
  File "<string>", line 550, in render
  File "<string>", line 1244, in lines
  File "<string>", line 348, in fetch_breakpoints
TypeError: '_sre.SRE_Match' object has no attribute '__getitem__'
```

**Comment by JsBlueCat** [comment]
i change 
```
 348:             what = catch_what_regex.search(' '.join(fields[4:]))[0].strip()
```
with 
```
 348:             what = catch_what_regex.search(' '.join(fields[4:])).group(0).strip()
```
and it pass

**Comment by cyrus-and** [comment]
Well spotted, thanks!
