### ISSUE TITLE
Cannot write the dashboard: [Errno 10] No child process

### ISSUE THREAD

**Issue by xeyownt** [cyrus-and/gdb-dashboard#56]
Hello,

I'm using dashboard to debug a custom cpu with a custom gdb back-end.
When starting the debugger, I frequently get the message

    Cannot write the dashboard: [Errno 10] No child process

To fix that I have to type `da` several times, until it works. When it works, it stay attached.

Any idea how I can debug that?
(this is on commit 379a81a)

**Comment by xeyownt** [comment]
Actually, no, it was not on commit 379a81a. Now I fast-forwarded, and here the traceback

```
Traceback (most recent call last):
  File "<string>", line 353, in render
  File "<string>", line 886, in lines
  File "<string>", line 200, in __init__
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 147, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pygments/lexers/__init__.py", line 112, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2290, in load
    self.require(*args, **kwargs)
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2307, in require
    items = working_set.resolve(reqs, env, installer)
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 861, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2551, in requires
    dm = self._dep_map
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2798, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2815, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2812, in reqs_for_extra
    if not req.marker or req.marker.evaluate({'extra': extra}):
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 283, in evaluate
    current_environment = default_environment()
  File "/home/xeyownt/.local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/markers.py", line 247, in default_environment
    "platform_machine": platform.machine(),
  File "/home/xeyownt/stm/stxp70_toolset_2016.1.3/python/lib/python2.7/platform.py", line 1347, in machine
    return uname()[4]
  File "/home/xeyownt/stm/stxp70_toolset_2016.1.3/python/lib/python2.7/platform.py", line 1277, in uname
    processor = _syscmd_uname('-p','')
  File "/home/xeyownt/stm/stxp70_toolset_2016.1.3/python/lib/python2.7/platform.py", line 1012, in _syscmd_uname
    rc = f.close()
IOError: [Errno 10] No child processes
```

**Comment by cyrus-and** [comment]
I'm assuming that the traceback is always the same (please check this) and not due to a *semi-random* event which happens to kill the Python process...

I can't exactly figure out why, but it looks like this problem is originated from:

```python
pygments.lexers.get_lexer_for_filename(filename)
```

so in the meantime try to completely disable syntax highlighting by placing the following in your init file:

    dashboard -style syntax_highlighting ''

Anyway it seems that the deeper part of the traceback concerns `stxp70_toolset_2016.1.3` which I assume is part of your custom CPU setup.

**Comment by cyrus-and** [comment]
Bump.

**Comment by xeyownt** [comment]
Hello, sorry for long delay.

Indeed, this was plain visible, but did not notice. I'll try your suggestion as soon as possible. Indeed, the toolchain I'm using provides its own Python implementation, so I guess this is the origin culprit.

**Comment by xeyownt** [comment]
Looking further in this problem, I could reproduce the problem easily with

```
python import platform; print platform.uname()
```

I reported the problem to the toolchain vendor. In the meantime I could fix it by patching the file `platform.py` that comes with the toolchain. This is probably not the best solution (hiding some underlying problem), but I'll go with that for now.

``` diff
@@ -1009,7 +1009,10 @@
     except (AttributeError,os.error):
         return default
     output = string.strip(f.read())
-    rc = f.close()
+    try:
+        rc = f.close()
+    except:
+        rc = 0
     if not output or rc:
         return default
     else:
```

In any case, the problem is not in gdb-dashboard.

**Comment by cyrus-and** [comment]
Good to know, thanks for the details.
