### ISSUE TITLE
Cannot write dashboard?

### ISSUE THREAD

**Issue by squidszyd** [cyrus-and/gdb-dashboard#66]
I don't know what happens here?

```
Breakpoint 1, main () at my_test.cpp:22
22		ts1 = ts1 + 2.0;
Cannot write the dashboard
Traceback (most recent call last):
  File "<string>", line 353, in render
  File "<string>", line 885, in lines
  File "<string>", line 200, in __init__
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 147, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "/usr/local/lib/python2.7/dist-packages/pygments/lexers/__init__.py", line 112, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "/usr/local/lib/python2.7/dist-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2301, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pexpect; sys_platform != "win32"' distribution was not found and is required by the application
```

**Comment by squidszyd** [comment]
Update the python modules fixed this problem.
