### ISSUE TITLE
name mt is not defined

### ISSUE THREAD

**Issue by SaravanaPunith** [cyrus-and/gdb-dashboard#9]
I am facing this error:
NameError: name 'mt' is not defined. Please help.

==========================
entire log:
Traceback (most recent call last):
  File "<string>", line 296, in <lambda>
  File "<string>", line 303, in on_continue
  File "<string>", line 257, in divider
  File "<string>", line 234, in ansi
NameError: name 'mt' is not defined
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.21-5.fc22.x86_64

Breakpoint 1, main () at delete_entire_list.c:48
48	        struct node *head = NULL;
Traceback (most recent call last):
  File "<string>", line 297, in <lambda>
  File "<string>", line 308, in on_stop
  File "<string>", line 339, in display
  File "<string>", line 801, in lines
  File "<string>", line 234, in ansi
NameError: name 'mt' is not defined

==========================

**Comment by cyrus-and** [comment]
What you're reporting is quite strange indeed. Line numbers do not match and the name `mt` is never used in the code, it seems that your `.gdbinit` is somewhat corrupted.

I'd suggest to erase every configuration file and try again:

    rm ~/.gdbinit
    rm -f -r ~/.gdbinit.d/
    wget -P ~ git.io/.gdbinit
